import { useEffect, useState } from "react"
import { useParams } from "react-router-dom"
import { uploadDestructionCertificate } from "@/api/mockApi"
import type { DestructionCertificate } from "@/api/types"
import { Card, CardContent } from "@/components/ui/card"
import { CheckCircle2, ShieldCheck, FileOutput } from "lucide-react"

export function CertificateView() {
  const { batchId } = useParams<{ batchId: string }>()
  const [cert, setCert] = useState<DestructionCertificate | null>(null)

  useEffect(() => {
    if (batchId) {
      uploadDestructionCertificate(batchId, 94).then(setCert)
    }
  }, [batchId])

  if (!cert) return <div className="p-8 text-center text-gray-500">Generating certificate...</div>

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex justify-between items-center">
        <h1 className="text-3xl font-bold text-gray-900">Destruction Certificate</h1>
        <div className="flex gap-2">
          <div className="flex items-center text-sm text-emerald-700 bg-emerald-50 px-3 py-1 rounded-full border border-emerald-200">
            <CheckCircle2 className="w-4 h-4 mr-2" />
            Certificate Verified
          </div>
          <div className="flex items-center text-sm text-blue-700 bg-blue-50 px-3 py-1 rounded-full border border-blue-200">
            <ShieldCheck className="w-4 h-4 mr-2" />
            Blockchain Verified
          </div>
        </div>
      </div>
      
      <Card className="border-2 border-gray-200 shadow-xl print:shadow-none bg-white">
        <CardContent className="p-12">
          <div className="border-b-2 border-gray-900 pb-8 mb-8 text-center">
            <FileOutput className="w-16 h-16 mx-auto text-gray-900 mb-4" />
            <h2 className="text-4xl font-serif font-bold text-gray-900 tracking-wide uppercase">Certificate of Destruction</h2>
            <p className="text-gray-500 mt-2 font-mono">ID: {cert.certificateId}</p>
          </div>

          <div className="grid grid-cols-2 gap-12 mb-12">
            <div>
              <h3 className="text-sm font-bold text-gray-400 uppercase tracking-wider mb-4">Batch Information</h3>
              <div className="space-y-4">
                <div>
                  <p className="text-sm text-gray-500">Batch ID</p>
                  <p className="text-lg font-mono font-bold">{cert.batchId}</p>
                </div>
                <div>
                  <p className="text-sm text-gray-500">Quantity Destroyed</p>
                  <p className="text-2xl font-bold text-red-600">{cert.quantityDestroyed} UNITS</p>
                </div>
              </div>
            </div>
            
            <div>
              <h3 className="text-sm font-bold text-gray-400 uppercase tracking-wider mb-4">Destruction Details</h3>
              <div className="space-y-4">
                <div>
                  <p className="text-sm text-gray-500">Date & Time</p>
                  <p className="font-medium">{new Date(cert.destructionDate).toLocaleString()}</p>
                </div>
                <div>
                  <p className="text-sm text-gray-500">Facility</p>
                  <p className="font-medium text-gray-900">{cert.facility.name}</p>
                  <p className="text-xs text-gray-500 font-mono">ID: {cert.facility.id}</p>
                </div>
              </div>
            </div>
          </div>

          <div className="bg-gray-50 rounded-lg p-6 border border-gray-200">
            <h3 className="text-sm font-bold text-gray-900 mb-4 flex items-center">
              <ShieldCheck className="w-5 h-5 mr-2 text-blue-500" />
              Cryptographic Proof
            </h3>
            <div className="space-y-3 font-mono text-xs text-gray-600 break-all">
              <p><strong className="text-gray-900">Certificate Hash:</strong> {cert.certificateHash}</p>
              <p><strong className="text-gray-900">Blockchain Tx:</strong> {cert.blockchainTxId}</p>
              <p><strong className="text-gray-900">Status:</strong> <span className="text-green-600 font-bold">VERIFIED</span></p>
            </div>
          </div>

          <div className="mt-16 text-center text-sm text-gray-400">
            <p>This is a regulatory compliant digital certificate generated by RxTrack.</p>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
