server:
  port: ${PORT:8081}

spring:
  application:
    name: reversechain
  profiles:
    default: local
  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/reversechaindb}
    username: ${SPRING_DATASOURCE_USERNAME:rc_user}
    password: ${SPRING_DATASOURCE_PASSWORD:rc_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET:4d284f18166d48259f63abf5bc439d57a9e52e468e82fa08842af58df24b17e4}
  expiration: 86400000 # 1 day

fraud:
  thresholds:
    low: 20
    medium: 50
    high: 80

# Dwell time thresholds (in days) for DELAYED_DISPATCH alerts
dwell-time:
  warning-threshold-days: 7
  critical-threshold-days: 14

fabric:
  enabled: false # Switched to clean in-database Key-Value SHA-256 Hash Store
blockchain:
  mode: hash-store # hash-store (default), fabric, or local
  channel-name: pharma-channel
  chaincode-name: pharma-contract
  peer-endpoint: localhost:7051
  override-auth: peer0.manufacturer.pharma.com
  msp-id: ManufacturerMSP
  crypto-path: ../fabric-network/organizations/peerOrganizations/manufacturer.pharma.com
