spring:
  application:
    name: reversechain

  datasource:
    url: jdbc:postgresql://localhost:5432/reversechaindb
    username: rc_user
    password: rc_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: 4d284f18166d48259f63abf5bc439d57a9e52e468e82fa08842af58df24b17e4
  expiration: 86400000 # 1 day

fraud:
  thresholds:
    low: 20
    medium: 50
    high: 80
